site_name: Workflow
theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.action.edit
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      primary: white
      accent: gray
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "Public Sans"
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
        warning: material/alert-decagram-outline

repo_name: ddeutils/ddeutil-workflow
repo_url: https://github.com/ddeutils/ddeutil-workflow

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ddeutils/ddeutil-workflow
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/korawica
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/korawica

nav:
  - Home:
    - index.md
    - Get Started: getting-started.md
    - Configuration: configuration.md
    - Context: context.md
  - API references:
    - Library:
      - Stages: api/stages.md
      - Event: api/event.md
      - Job: api/job.md
      - Workflow: api/workflow.md
      - Params: api/params.md
      - Result: api/result.md
      - Reusables: api/reusables.md
      - Traces: api/traces.md
      - Audits: api/audits.md
      - Utils: api/utils.md
      - Errors: api/errors.md
  - Examples:
      - RestAPI: examples/api.md
      - Postgres: examples/pg.md

plugins:
  - tags
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/ddeutils/ddeutil-workflow" target="_blank" rel="noopener">DDEUtils Organization</a>
