name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'tests/'

jobs:

  docker-image:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Build Docker Image
        run: |
          docker build -t ddeutil-workflow:python${{ matrix.python-version }} -f .container/Dockerfile .
          docker image ls
