name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'tests/'

jobs:

  docker-image:
    runs-on: ubuntu-latest
    environment:
      name: github-image
      url: https://github.com/ddeutils/ddeutil-workflow/pkgs/container/ddeutil-workflow
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Show GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Set up Docker Buildx
#        run: |
#          docker buildx ls
#          docker buildx create --use

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set date
        id: date
        run: echo "name=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT

      - name: Build the dfa-fastapi Docker image
        run: |
          docker buildx build \
            --no-cache \
            --file ./.container/Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ vars.GH_REPO_URL }}:latest \
            --push .
