name: build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'tests/'

jobs:

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the dfa-fastapi Docker image
        run: |
          docker build -t ${{ vars.GH_REPO_URL }}:latest -f ./.container/Dockerfile .
          docker push ${{ vars.GH_REPO_URL }}:latest
