name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'

jobs:

  docker-image:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
